### ISSUE TITLE
plugin for tokenization/segmentation

### ISSUE THREAD

**Issue by balmas** [PerseusDL/cts-js#7]
the next step in a client-side annotation workflow after we have the CTS passage is to segment/tokenize it and prepare a template for annotation.

The alpheios treebank input form models this as follows:

We have a metadata element in the page which describes the tokenization options:

https://github.com/alpheios-project/treebank-editor/blob/master/db/app/treebank-entertext-perseids.xhtml#L42
  `<!-- default url to the tokenization service to use to process the input text.
can be overridden per language.`
     `- @content contains the base url for the tokenizatoin service POST`
     `- @data-params contains the names of input elements from the form which should
be forwarded to the tokenization service. The format of this is a space separated list of
attribute names. the attribute names optionally can be | separated map from the name of this
parameter in the input form to the name of the parameter on the tokenization service.
this is a complete hack but was a quick and dirty way to reuse the existing form`
      `- @data-transform contains the path to the XSLT transformation to apply to the tokenization
service output to create the treebank template for posting to to the back end storage service``
`    -->`
`
`
    <meta name="tokenization_service"
    content="http://services.perseids.org/llt/segtok"
    data-params="xml inline split-tokens|splitting merge-tokens|merging shift-tokens|shifting     inputtext|text remove_node[] go_to_root ns"
    data-transform="../xslt/segtok_to_tb.xsl"/>
`
And equivalent input elements to control these options (split-tokens, merge-tokens, shift-tokens, etc.)

Upon  upload of text into the text input box, we submit it to the tokenization service with the options from the form. See code starting at https://github.com/alpheios-project/treebank-editor/blob/master/db/script/alph-treebank-enter.js#L200

It would be very cool to have an add-on plugin for the cts selector which provided this functionality.

**Comment by balmas** [comment]
For reference, may also be useful to see 

https://github.com/PerseusDL/perseids_docs/wiki/Requirements-for-Annotation-Template-Creation
https://github.com/PerseusDL/perseids_docs/issues/194
https://github.com/PerseusDL/perseids_docs/issues/137

**Comment by balmas** [comment]
a key to the current llt segtok service options (@LFDM please let me know if I've missed any):

text = text string to segment/tokenize
xml = true|false (whether or not supplied text is XML)
splitting = true|false (whether or not to split enclytics) [ default is true for treebanking in Perseids ]
merging = true|false (whether or not to merge specific words that should be ... this is a very small  language-specific set) [default is false for treebanking in Perseids ]
shifting = true|false (whether or not to reverse the order of split enclytics) [ default is false for treebanking in Perseids ]
remove_node[] = name of a xml XML node to ignore in the tokenization (multi-value param)
go_to_root = name of node in the input to consider as the root of the document
ns = namespace of the xml text

**Comment by PonteIneptique** [comment]
Thought options for the jQuery plugin (not the abstraction)

jQuery.cts.service // Make every CTS.Service available

Options : 
| Key | Informations
| ----- |
| serviceName | default("llt.tokenizer")
| onTrigger | Default(False) else string,
| onClick | Default(False) else selector string or $(element),
| existingValue | dictionary where you tie options of a service with an element in the window,
| overrideDefaults | override CTS.service.new(serviceName).options[value].default,
| show | true|false|on(string) -> Show the parameter (true, false, on a certain trigger)

**Comment by PonteIneptique** [comment]
Renamed some stuff, serviceName will be a parameter on init and not a setting.

| Key              | type           | Default       | Informations
| ---------------- | -------------- | ------------- | -----------------------------------
| trigger          | string         | null          | Link sending data of the 
| click            | string,element | false         | Send request on click
| existingValue    | dictionary     | {}            | where you tie options of a service with an element in the window,
| overrideDefaults | dictionary     | {}            | override CTS.service.new(serviceName).options[value].default,
| show             | boolean,string | true          | on(string) -> Show the parameter (true, false, on a certain trigger $().on("triggrer"))
| callback         | function       | null          | Function to trigger

**Comment by PonteIneptique** [comment]
Proposed fix in #16 , not checked by @balmas

**Comment by balmas** [comment]
@PonteIneptique  the cts-selector branch of the treebank editor code is where you can find my changes to include it there. https://github.com/alpheios-project/treebank-editor/compare/cts-selector?expand=1  I added a new treebank-entertext-arethusa-stage.xhtml page and made a minor adjustment to the supporting javascript.  NB I would REALLY like not to have to have different versions of this xhtml file for each deployment environment and I would also like to deploy this simply on the document root and not the eXist database. This whole approach was intended to be a temporary solution until we had the client side plugin components you are now building.  SO if it makes more sense for you to build a completely new form that replaces the current treebank and alignment editor input forms, this is 100% okay with me!
